Made `dashboard` responsive.
HirbodBehnam/Webdev-1401 pull request #12
Opened 2022-12-08 14:04 UTC by sorousherafat

2022-12-08 14:54 UTC, HirbodBehnam reviewed
![image](https://user-images.githubusercontent.com/11520090/206478953-7f36faf2-5390-42cc-bb1c-916d4fe53f69.png)
این هم وسط چین بشه خوبه. ولی مشکلی که هست اینه که عددا از کادر زده بیرون... این مسافران هم اگر بتونی کلا بندازی زیر هم به نظرم خیلی خوبه

2022-12-08 14:57 UTC, HirbodBehnam requested changes
به نظرم flight result رو میشه یه جوری جمعش کرد اون رو تحویل داد ولی اینو حس میکنم جدی نمیشه با این وضعیت تحویل داد😂

2022-12-09 13:18 UTC, sorousherafat commented
![image](https://user-images.githubusercontent.com/71870584/206710988-bedc6a9d-97e0-40ff-989b-50bb61fb19ed.png)

![image](https://user-images.githubusercontent.com/71870584/206711122-085ca93e-6832-4ea9-a79b-b073d0a7c9f5.png)

2022-12-09 13:59 UTC, HirbodBehnam approved these changes
خیلی خوب شد واقعا.
جدوله فوق العاده زیبا شد✅

2022-12-09 14:00 UTC, merged